### ISSUE TITLE
TypeError: 'TraversibleType' object is not subscriptable

### ISSUE THREAD

**Issue by zufanka** [alephdata/followthemoney#670]
Hi! When running any `ftm` command I get:

```
(base) ~ ♥ ftm --help
Traceback (most recent call last):
  File "/home/zufank/anaconda3/bin/ftm", line 5, in <module>
    from followthemoney.cli.cli import cli
  File "/home/zufank/anaconda3/lib/python3.9/site-packages/followthemoney/__init__.py", line 3, in <module>
    from followthemoney.model import Model
  File "/home/zufank/anaconda3/lib/python3.9/site-packages/followthemoney/model.py", line 9, in <module>
    from followthemoney.mapping import QueryMapping
  File "/home/zufank/anaconda3/lib/python3.9/site-packages/followthemoney/mapping/__init__.py", line 1, in <module>
    from followthemoney.mapping.query import QueryMapping
  File "/home/zufank/anaconda3/lib/python3.9/site-packages/followthemoney/mapping/query.py", line 6, in <module>
    from followthemoney.mapping.sql import SQLSource
  File "/home/zufank/anaconda3/lib/python3.9/site-packages/followthemoney/mapping/sql.py", line 46, in <module>
    class SQLSource(Source):
  File "/home/zufank/anaconda3/lib/python3.9/site-packages/followthemoney/mapping/sql.py", line 66, in SQLSource
    def get_column(self, ref: Optional[str]) -> Label[Any]:
TypeError: 'TraversibleType' object is not subscriptable
```
I'm on Fedora 35
python 3.9
pip 22.0.4

Here are all the packages versions:

```
(base) ~ ♥ python -m pip install --upgrade followthemoney
Requirement already satisfied: followthemoney in ./anaconda3/lib/python3.9/site-packages (2.9.1)
Requirement already satisfied: babel<3.0.0,>=2.9.1 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (2.9.1)
Requirement already satisfied: python-levenshtein<1.0.0,>=0.12.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (0.12.2)
Requirement already satisfied: openpyxl<4.0.0,>=3.0.5 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (3.0.9)
Requirement already satisfied: pyyaml<7.0.0,>=5.0.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (6.0)
Requirement already satisfied: fuzzywuzzy[speedup]<1.0.0,>=0.18.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (0.18.0)
Requirement already satisfied: types-PyYAML in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (6.0.7)
Requirement already satisfied: fingerprints<2.0.0,>=1.0.1 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (1.0.3)
Requirement already satisfied: normality<3.0.0,>=2.1.1 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (2.2.5)
Requirement already satisfied: prefixdate<1.0.0,>=0.4.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (0.4.1)
Requirement already satisfied: sqlalchemy2-stubs in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (0.0.2a22)
Requirement already satisfied: sqlalchemy<2.0.0,>=1.2.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (1.4.22)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (2.26.0)
Requirement already satisfied: phonenumbers<9.0.0,>=8.12.22 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (8.12.48)
Requirement already satisfied: click<9.0.0,>=7.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (7.1.2)
Requirement already satisfied: pantomime<1.0.0,>=0.5.1 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (0.5.1)
Requirement already satisfied: pytz>=2021.1 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (2021.3)
Requirement already satisfied: networkx<2.9,>=2.5 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (2.6.3)
Requirement already satisfied: stringcase<2.0.0,>=1.2.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (1.2.0)
Requirement already satisfied: languagecodes<2.0.0,>=1.1.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (1.1.1)
Requirement already satisfied: rdflib<6.2.0,>=6.1.0 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (6.1.1)
Requirement already satisfied: countrynames<2.0.0,>=1.9.1 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (1.11.1)
Requirement already satisfied: python-stdnum<2.0.0,>=1.16 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (1.17)
Requirement already satisfied: banal<1.1.0,>=1.0.1 in ./anaconda3/lib/python3.9/site-packages (from followthemoney) (1.0.6)
Requirement already satisfied: text-unidecode in ./anaconda3/lib/python3.9/site-packages (from normality<3.0.0,>=2.1.1->followthemoney) (1.3)
Requirement already satisfied: chardet in ./anaconda3/lib/python3.9/site-packages (from normality<3.0.0,>=2.1.1->followthemoney) (4.0.0)
Requirement already satisfied: et-xmlfile in ./anaconda3/lib/python3.9/site-packages (from openpyxl<4.0.0,>=3.0.5->followthemoney) (1.1.0)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.9/site-packages (from python-levenshtein<1.0.0,>=0.12.0->followthemoney) (58.0.4)
Requirement already satisfied: pyparsing in ./anaconda3/lib/python3.9/site-packages (from rdflib<6.2.0,>=6.1.0->followthemoney) (3.0.4)
Requirement already satisfied: isodate in ./anaconda3/lib/python3.9/site-packages (from rdflib<6.2.0,>=6.1.0->followthemoney) (0.6.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.21.0->followthemoney) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.21.0->followthemoney) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.21.0->followthemoney) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in ./anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.21.0->followthemoney) (3.2)
Requirement already satisfied: greenlet!=0.4.17 in ./anaconda3/lib/python3.9/site-packages (from sqlalchemy<2.0.0,>=1.2.0->followthemoney) (1.1.1)
Requirement already satisfied: typing-extensions>=3.7.4 in ./anaconda3/lib/python3.9/site-packages (from sqlalchemy2-stubs->followthemoney) (3.10.0.2)
Requirement already satisfied: six in ./anaconda3/lib/python3.9/site-packages (from isodate->rdflib<6.2.0,>=6.1.0->followthemoney) (1.16.0)
```

Is there something I can do?

**Comment by pudo** [comment]
Hmm, there's no obvious answer here. Can you maybe do a `pip install -U sqlalchemy sqlalchemy2-stubs` and see if the issue still occurs?

**Comment by zufanka** [comment]
🧡! Thank you, this works
