### ISSUE TITLE
[Memorious] Error: "followthemoney.exc.InvalidModel: Invalid type: gender" when setting the FTM_MODEL_PATH env var

### ISSUE THREAD

**Issue by Julm** [alephdata/followthemoney#762]
Context:
I'm trying (hard) to extend the FtM schema with a new entity.

I'm running Memorious with `FTM_MODEL_PATH` set to a specific directory for override.
The directory contains a copy of FtM `schema` directory.
The directory is well mounted and YAML files are accessible from within the Docker container 

dockercompose.yml
```
volumes:
      - "./build/data:/data"
      - "./config:/crawlers/config"
      - "./src:/crawlers/src"
      - "./ftm-schema:/data/ftm-schema"
 env_file:
      - memorious.env
```
 
memorious.env
```
FTM_MODEL_PATH=/data/ftm-schema
```

The error happens at loading time, whatever the scraper being run.

```
root@5cc7cbcfeefc:/memorious# memorious run malta_tenders_scraper
2022-07-12 14:42:53.209217 [info     ] [malta_tenders_scraper->init(seed)]: 09287abea50e4928982f9ee4896380fc [malta_tenders_scraper.init]
2022-07-12 14:42:54.136851 [error    ] Invalid type: gender           [malta_tenders_scraper.init]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/memorious/logic/context.py", line 93, in execute
    return self.stage.method(self, data)
  File "/usr/local/lib/python3.8/dist-packages/memorious/logic/stage.py", line 23, in method
    func = get_entry_point("memorious.operations", self.method_name)
  File "/usr/local/lib/python3.8/dist-packages/servicelayer/extensions.py", line 21, in get_entry_point
    return get_entry_points(section).get(name)
  File "/usr/local/lib/python3.8/dist-packages/servicelayer/extensions.py", line 16, in get_entry_points
    EXTENSIONS[section][ep.name] = ep.load()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2458, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2464, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/memorious/operations/ftm.py", line 2, in <module>
    from ftmstore import get_dataset as get_ftmstore_dataset
  File "/usr/local/lib/python3.8/dist-packages/ftmstore/__init__.py", line 4, in <module>
    from ftmstore.store import Store
  File "/usr/local/lib/python3.8/dist-packages/ftmstore/store.py", line 6, in <module>
    from ftmstore.dataset import Dataset
  File "/usr/local/lib/python3.8/dist-packages/ftmstore/dataset.py", line 5, in <module>
    from followthemoney import model
  File "/usr/local/lib/python3.8/dist-packages/followthemoney/__init__.py", line 14, in <module>
    model = Model(model_path)
  File "/usr/local/lib/python3.8/dist-packages/followthemoney/model.py", line 37, in __init__
    self._load(os.path.join(path, filename))
  File "/usr/local/lib/python3.8/dist-packages/followthemoney/model.py", line 61, in _load
    self.schemata[name] = Schema(self, name, config)
  File "/usr/local/lib/python3.8/dist-packages/followthemoney/schema.py", line 186, in __init__
    self.properties[name] = Property(self, name, prop)
  File "/usr/local/lib/python3.8/dist-packages/followthemoney/property.py", line 94, in __init__
    raise InvalidModel("Invalid type: %s" % type_)
followthemoney.exc.InvalidModel: Invalid type: gender
```

**Comment by pudo** [comment]
I'm pretty sure this is a mismatch between the version of FtM from which you took the model files you're using and the version that's installed. Maybe you can run this:

```bash
$ python 
> from followthemoney import __version__
> print(__version__)
```

If this is older than, say, 2.9.0 or 2.8.0, then it doesn't have a `gender` type yet. Maybe solvable with brutality: `pip install -U followthemoney` :)
