### ISSUE TITLE
Entity to triple datetime issue

### ISSUE THREAD

**Issue by PeterWalchhofer** [alephdata/followthemoney#834]
When I want to call `triples()` on an EntityProxy and the date is formatted like this `2021-02-10` a exception message of rdflib is printed. When transforming 12k entities to RDF this kills my jupyter kernel. AFAIK the error is that Instead of XSD.dateTime the date should be converted to XSD.date

Example:
`entity.to_dict()`
```
{'origin': 'memorious',
 'id': '00002ace5898c73114244ac0004dff18b6fcc9eb',
 'schema': 'Membership',
 'properties': {'description': ['Kommanditist [285384h]'],
  'endDate': ['2021-02-10'],
  'member': ['98ac0209f5c11c5aeaf03cae2d60eb08dd383006'],
  'organization': ['52df103971e47b36550707db4c4a0c727e672785'],
  'startDate': ['2017-09-15']}}
```

`list(entity.triples())`

```
Traceback (most recent call last):
  File "/home/peter/.local/lib/python3.10/site-packages/rdflib/term.py", line 2084, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/home/peter/.local/lib/python3.10/site-packages/isodate/isodatetime.py", line 53, in parse_datetime
    raise ISO8601Error("ISO 8601 time designator 'T' missing. Unable to"
isodate.isoerror.ISO8601Error: ISO 8601 time designator 'T' missing. Unable to parse datetime string '2021-02-10'
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#dateTime, Converter=<function parse_datetime at 0x7f9f21538f70>
Traceback (most recent call last):
  File "/home/peter/.local/lib/python3.10/site-packages/isodate/isodatetime.py", line 51, in parse_datetime
    datestring, timestring = datetimestring.split('T')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by pudo** [comment]
Ha, I just stumbled over the same thing the other day and fixed it in main: https://github.com/alephdata/followthemoney/commit/258e7ba0683cf82d5f7f865f7ad365e60903bcf6

Should be gone in the next release. @Rosencrantz mind I push one out today? Nothing big has happened but it might be cool with all the dep updates, too.

**Comment by Rosencrantz** [comment]
That should be fine. Please let us know once you've pushed out the release.

**Comment by PeterWalchhofer** [comment]
Yiha, that was fast! Thank you :)
